#ifndef CUBE_GENERATED_MAIN_H
#define CUBE_GENERATED_MAIN_H

#include "stm32g4xx_hal.h"

#define PRECHARGE_DRV_Pin GPIO_PIN_0
#define PRECHARGE_DRV_GPIO_Port GPIOA
#define MAIN_CONTACTOR_DRV_Pin GPIO_PIN_1
#define MAIN_CONTACTOR_DRV_GPIO_Port GPIOA
#define DEBUG_UART_TX_Pin GPIO_PIN_2
#define DEBUG_UART_TX_GPIO_Port GPIOA
#define DEBUG_UART_RX_Pin GPIO_PIN_3
#define DEBUG_UART_RX_GPIO_Port GPIOA
#define PACK_VOLTAGE_ADC_Pin GPIO_PIN_4
#define PACK_VOLTAGE_ADC_GPIO_Port GPIOA
#define BUS_VOLTAGE_ADC_Pin GPIO_PIN_5
#define BUS_VOLTAGE_ADC_GPIO_Port GPIOA
#define NTC_TEMPERATURE_ADC_Pin GPIO_PIN_6
#define NTC_TEMPERATURE_ADC_GPIO_Port GPIOA
#define PRECHARGE_FB_Pin GPIO_PIN_0
#define PRECHARGE_FB_GPIO_Port GPIOB
#define MAIN_CONTACTOR_FB_Pin GPIO_PIN_1
#define MAIN_CONTACTOR_FB_GPIO_Port GPIOB
#define INA228_SCL_Pin GPIO_PIN_6
#define INA228_SCL_GPIO_Port GPIOB
#define INA228_SDA_Pin GPIO_PIN_7
#define INA228_SDA_GPIO_Port GPIOB
#define FDCAN1_RX_Pin GPIO_PIN_8
#define FDCAN1_RX_GPIO_Port GPIOB
#define FDCAN1_TX_Pin GPIO_PIN_9
#define FDCAN1_TX_GPIO_Port GPIOB

void Error_Handler(void);

#endif
